spring:
  application:
  name: rabbitmq-extensions-demo

  #配置rabbitmq的基本信息
  rabbitmq:
    addresses: amqp://edison:edison@8.156.77.78:5672/extension
    listener:
      simple:
        #acknowledge-mode: none # 消息接收确认(自动确认)
        #acknowledge-mode: auto # 消息接收确认
        acknowledge-mode: manual # 消息接收确认
    #publisher-confirm-type: correlated  # 消息发送确认(confirm模式 --- 站点收到了快递)
    publisher-confirm-type: correlated  # 消息发送确认(confirm模式 --- 站点收到了无法送到的快递, 那么需要把快递退回)
